# Generated by Django 6.1.1 on 2026-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, verbose_name='Phone / WhatsApp')),
                ('business_type', models.CharField(choices=[('business', 'Business Website'), ('restaurant', 'Restaurant / Cafe'), ('salon', 'Salon / Beauty'), ('ecommerce', 'E-commerce'), ('real_estate', 'Real Estate'), ('clinic', 'Doctor / Clinic'), ('portfolio', 'Portfolio'), ('custom', 'Custom Web Application'), ('other', 'Other')], default='other', max_length=20)),
                ('website_requirement', models.CharField(choices=[('new', 'New Website'), ('redesign', 'Website Redesign'), ('ecommerce', 'E-commerce Store'), ('webapp', 'Custom Web Application'), ('not_sure', 'Not Sure Yet')], default='new', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
